# Generated by Django 2.1.15 on 2021-03-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_state', models.CharField(max_length=64, verbose_name='订单状态')),
                ('paper_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64, verbose_name='商品名')),
                ('product_brand', models.CharField(max_length=64, verbose_name='标签')),
                ('product_img', models.CharField(max_length=128, verbose_name='封面地址')),
                ('detail_img', models.CharField(max_length=128, verbose_name='描述地址')),
                ('product_sales', models.IntegerField(verbose_name='购买数量')),
                ('product_cost', models.FloatField(verbose_name='价钱')),
                ('product_color', models.CharField(max_length=64, verbose_name='颜色')),
                ('product_state', models.CharField(max_length=64, verbose_name='使用程度')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='昵称')),
                ('user_username', models.CharField(max_length=64, verbose_name='用户名')),
                ('user_password', models.CharField(max_length=64, verbose_name='密码')),
                ('user_state', models.BooleanField(default=False)),
                ('user_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
