# Generated by Django 2.1.15 on 2021-03-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_paper_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='produce_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='producer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
